net: bus: decrement the socket reference count on bus_add_addr()
bus_peer_get() grabs a the peer socket reference count so the refcount has to
be decremented after using the socket peer.

Not ungrabbing the peer socket reference count leads to the error of not
allowing the bus kernel module to be removed:

ERROR: Module bus is in use

Signed-off-by: Javier Martinez Canillas <javier.martinez@collabora.co.uk>